export { default as Categories } from './categories/index.jsx';
export { default as Products } from './products/index.jsx';
export { default as ProductDetail } from "./product-detail/index.jsx"
export { default as Orders } from "./orders/index.jsx"
export { default as Cart } from "./cart/index.jsx"
export { default as Auth } from "./auth/index.jsx"
export { default as Settings } from "./settings/index.jsx"
export { default as Address } from "./address/index.jsx"
export { default as Profile } from "./profile/index.jsx"